import {
    ClientMessageFtAction,
    ClientMessageFtAddTime,
    ClientMessageFtAutoOpActive,
    ClientMessageFtBringIn,
    ClientMessageFtBroadcastMsg,
    ClientMessageFtChatMembers,
    ClientMessageFtEnterRoom,
    ClientMessageFtKeepSeatActive,
    ClientMessageFtLeave,
    ClientMessageFtObservers,
    ClientMessageFtPair,
    ClientMessageFtPrivateMsg,
    ClientMessageFtPublicReplay,
    ClientMessageFtRoomers,
    ClientMessageFtSeated,
    ClientMessageFtSetAutoOnTable,
    ClientMessageFtStandupActive,
    ClientMessageFtSyncEnter,
    Code,
    ServerMessageFtAction,
    ServerMessageFtActionAll,
    ServerMessageFtAddTime,
    ServerMessageFtAddTimeOthers,
    ServerMessageFtAutoOp,
    ServerMessageFtAutoOpActive,
    ServerMessageFtBringIn,
    ServerMessageFtBringInFail,
    ServerMessageFtBroadcastMsg,
    ServerMessageFtChatMembers,
    ServerMessageFtChipsChange,
    ServerMessageFtEnterRoom,
    ServerMessageFtGetMsg,
    ServerMessageFtHandClear,
    ServerMessageFtKeepSeat,
    ServerMessageFtKeepSeatActive,
    ServerMessageFtLeave,
    ServerMessageFtLeaveNotification,
    ServerMessageFtObservers,
    ServerMessageFtPair,
    ServerMessageFtPairAll,
    ServerMessageFtPrivateMsg,
    ServerMessageFtPublicCards,
    ServerMessageFtPublicReplay,
    ServerMessageFtRoomers,
    ServerMessageFtSeated,
    ServerMessageFtSeatedOthers,
    ServerMessageFtSetAutoOnTable,
    ServerMessageFtStandup,
    ServerMessageFtStandupActive,
    ServerMessageFtStartInfo,
    ServerMessageFtSyncEnter,
    ServerMessageFtVideoMaskChange,
    ServerMessageFtWinner
} from '@silenthill/agreement-web';

export const CodeMessageFantasyClientGC = {
    [Code.MSG_D_FT_ENTER_ROOM]: [ClientMessageFtEnterRoom, null! as ClientMessageFtEnterRoom.AsObject],
    [Code.MSG_D_FT_SEATED]: [ClientMessageFtSeated, null! as ClientMessageFtSeated.AsObject],
    [Code.MSG_D_FT_BRING_IN]: [ClientMessageFtBringIn, null! as ClientMessageFtBringIn.AsObject],
    [Code.MSG_D_FT_ACTION]: [ClientMessageFtAction, null! as ClientMessageFtAction.AsObject],
    [Code.MSG_D_FT_AUTO_OP_ACTIVE]: [ClientMessageFtAutoOpActive, null! as ClientMessageFtAutoOpActive.AsObject],
    [Code.MSG_D_FT_STANDUP_ACTIVE]: [ClientMessageFtStandupActive, null! as ClientMessageFtStandupActive.AsObject],
    [Code.MSG_D_FT_LEAVE]: [ClientMessageFtLeave, null! as ClientMessageFtLeave.AsObject],
    [Code.MSG_D_FT_KEEP_SEAT_ACTIVE]: [ClientMessageFtKeepSeatActive, null! as ClientMessageFtKeepSeatActive.AsObject],
    [Code.MSG_D_FT_ADD_TIME]: [ClientMessageFtAddTime, null! as ClientMessageFtAddTime.AsObject],
    [Code.MSG_D_FT_PUBLIC_REPLAY]: [ClientMessageFtPublicReplay, null! as ClientMessageFtPublicReplay.AsObject],
    [Code.MSG_D_FT_BROADCAST_MSG]: [ClientMessageFtBroadcastMsg, null! as ClientMessageFtBroadcastMsg.AsObject],
    [Code.MSG_D_FT_PRIVATE_MSG]: [ClientMessageFtPrivateMsg, null! as ClientMessageFtPrivateMsg.AsObject],
    [Code.MSG_D_FT_ROOMERS]: [ClientMessageFtRoomers, null! as ClientMessageFtRoomers.AsObject],
    [Code.MSG_D_FT_SET_AUTO_ON_TABLE]: [ClientMessageFtSetAutoOnTable, null! as ClientMessageFtSetAutoOnTable.AsObject],
    [Code.MSG_D_FT_PAIR]: [ClientMessageFtPair, null! as ClientMessageFtPair.AsObject],
    [Code.MSG_D_FT_OBSERVERS]: [ClientMessageFtObservers, null! as ClientMessageFtObservers.AsObject],
    [Code.MSG_D_FT_SYNC_ENTER]: [ClientMessageFtSyncEnter, null! as ClientMessageFtSyncEnter.AsObject],
    [Code.MSG_D_FT_CHAT_MEMBERS]: [ClientMessageFtChatMembers, null! as ClientMessageFtChatMembers.AsObject]
} as const;

export type CodeMessageFantasyClientGC = typeof CodeMessageFantasyClientGC;

export const CodeMessageFantasyServerGC = {
    [Code.MSG_D_FT_ENTER_ROOM]: ServerMessageFtEnterRoom,
    [Code.MSG_D_FT_SEATED]: ServerMessageFtSeated,
    [Code.MSG_D_FT_BRING_IN]: ServerMessageFtBringIn,
    [Code.MSG_D_FT_ACTION]: ServerMessageFtAction,
    [Code.MSG_D_FT_AUTO_OP_ACTIVE]: ServerMessageFtAutoOpActive,
    [Code.MSG_D_FT_STANDUP_ACTIVE]: ServerMessageFtStandupActive,
    [Code.MSG_D_FT_LEAVE]: ServerMessageFtLeave,
    [Code.MSG_D_FT_KEEP_SEAT_ACTIVE]: ServerMessageFtKeepSeatActive,
    [Code.MSG_D_FT_ADD_TIME]: ServerMessageFtAddTime,
    [Code.MSG_D_FT_PUBLIC_REPLAY]: ServerMessageFtPublicReplay,
    [Code.MSG_D_FT_BROADCAST_MSG]: ServerMessageFtBroadcastMsg,
    [Code.MSG_D_FT_PRIVATE_MSG]: ServerMessageFtPrivateMsg,
    [Code.MSG_D_FT_ROOMERS]: ServerMessageFtRoomers,
    [Code.MSG_D_FT_SET_AUTO_ON_TABLE]: ServerMessageFtSetAutoOnTable,
    [Code.MSG_D_FT_PAIR]: ServerMessageFtPair,
    [Code.MSG_D_FT_OBSERVERS]: ServerMessageFtObservers,
    [Code.MSG_D_FT_SYNC_ENTER]: ServerMessageFtSyncEnter,
    [Code.MSG_D_FT_CHAT_MEMBERS]: ServerMessageFtChatMembers,
    [Code.MSG_S_FT_SEATED_OTHERS]: ServerMessageFtSeatedOthers,
    [Code.MSG_S_FT_START_INFO]: ServerMessageFtStartInfo,
    [Code.MSG_S_FT_PUBLIC_CARDS]: ServerMessageFtPublicCards,
    [Code.MSG_S_FT_CHIPS_CHANGE]: ServerMessageFtChipsChange,
    [Code.MSG_S_FT_ACTION_ALL]: ServerMessageFtActionAll,
    [Code.MSG_S_FT_AUTO_OP]: ServerMessageFtAutoOp,
    [Code.MSG_S_FT_STANDUP]: ServerMessageFtStandup,
    [Code.MSG_S_FT_KEEP_SEAT]: ServerMessageFtKeepSeat,
    [Code.MSG_S_FT_WINNER]: ServerMessageFtWinner,
    [Code.MSG_S_FT_ADD_TIME_OTHERS]: ServerMessageFtAddTimeOthers,
    [Code.MSG_S_FT_LEAVE_NOTIFICATION]: ServerMessageFtLeaveNotification,
    [Code.MSG_S_FT_BRING_IN_FAIL]: ServerMessageFtBringInFail,
    [Code.MSG_S_FT_HAND_CLEAR]: ServerMessageFtHandClear,
    [Code.MSG_S_FT_GET_MSG]: ServerMessageFtGetMsg,
    [Code.MSG_S_FT_PAIR_ALL]: ServerMessageFtPairAll,
    [Code.MSG_S_FT_VIDEO_MASK_CHANGE]: ServerMessageFtVideoMaskChange
} as const;

export type CodeMessageFantasyServerGC = typeof CodeMessageFantasyServerGC;
