import {
    ClientMessageMjAction,
    ClientMessageMjAddTime,
    ClientMessageMjAutoOpActive,
    ClientMessageMjBringIn,
    ClientMessageMjBroadcastMsg,
    ClientMessageMjChatMembers,
    ClientMessageMjEnterRoom,
    ClientMessageMjExchangeTiles,
    ClientMessageMjKeepSeatActive,
    ClientMessageMjLeave,
    ClientMessageMjObservers,
    ClientMessageMjPrivateMsg,
    ClientMessageMjRaise,
    ClientMessageMjRejectBringIn,
    ClientMessageMjReplay,
    ClientMessageMjRoomers,
    ClientMessageMjSeated,
    ClientMessageMjSetAutoOnTable,
    ClientMessageMjStandupActive,
    ClientMessageMjSyncEnter,
    ClientMessageMjVoidSuit,
    Code,
    ServerMessageMjAction,
    ServerMessageMjActionAll,
    ServerMessageMjActionFail,
    ServerMessageMjAddTime,
    ServerMessageMjAddTimeOthers,
    ServerMessageMjAutoOp,
    ServerMessageMjAutoOpActive,
    ServerMessageMjBringIn,
    ServerMessageMjBringInFail,
    ServerMessageMjBroadcastMsg,
    ServerMessageMjChatMembers,
    ServerMessageMjChipsChange,
    ServerMessageMjEnterRoom,
    ServerMessageMjExchangeTiles,
    ServerMessageMjExchangeTilesComplete,
    ServerMessageMjFollowDealer,
    ServerMessageMjGetMsg,
    ServerMessageMjHandClear,
    ServerMessageMjKeepSeat,
    ServerMessageMjKeepSeatActive,
    ServerMessageMjLeave,
    ServerMessageMjLeaveNotification,
    ServerMessageMjNeedBringIn,
    ServerMessageMjNeedBringInComplete,
    ServerMessageMjObservers,
    ServerMessageMjPrepare,
    ServerMessageMjPrivateMsg,
    ServerMessageMjRaise,
    ServerMessageMjRaiseComplete,
    ServerMessageMjRejectBringIn,
    ServerMessageMjReplay,
    ServerMessageMjResult,
    ServerMessageMjRoomers,
    ServerMessageMjSeated,
    ServerMessageMjSeatedOthers,
    ServerMessageMjSetAutoOnTable,
    ServerMessageMjStandup,
    ServerMessageMjStandupActive,
    ServerMessageMjStartInfo,
    ServerMessageMjSyncEnter,
    ServerMessageMjSyncHand,
    ServerMessageMjUpBlind,
    ServerMessageMjVideoMaskChange,
    ServerMessageMjVoidSuit,
    ServerMessageMjVoidSuitComplete,
    ServerMessageMjWaitTurnAction
} from '@silenthill/agreement-web';

export const CodeMessageMahjongClientGC = {
    [Code.MSG_D_MJ_ENTER_ROOM]: [ClientMessageMjEnterRoom, null! as ClientMessageMjEnterRoom.AsObject],
    [Code.MSG_D_MJ_SEATED]: [ClientMessageMjSeated, null! as ClientMessageMjSeated.AsObject],
    [Code.MSG_D_MJ_BRING_IN]: [ClientMessageMjBringIn, null! as ClientMessageMjBringIn.AsObject],
    [Code.MSG_D_MJ_EXCHANGE_TILES]: [ClientMessageMjExchangeTiles, null! as ClientMessageMjExchangeTiles.AsObject],
    [Code.MSG_D_MJ_VOID_SUIT]: [ClientMessageMjVoidSuit, null! as ClientMessageMjVoidSuit.AsObject],
    [Code.MSG_D_MJ_ACTION]: [ClientMessageMjAction, null! as ClientMessageMjAction.AsObject],
    [Code.MSG_D_MJ_AUTO_OP_ACTIVE]: [ClientMessageMjAutoOpActive, null! as ClientMessageMjAutoOpActive.AsObject],
    [Code.MSG_D_MJ_STANDUP_ACTIVE]: [ClientMessageMjStandupActive, null! as ClientMessageMjStandupActive.AsObject],
    [Code.MSG_D_MJ_LEAVE]: [ClientMessageMjLeave, null! as ClientMessageMjLeave.AsObject],
    [Code.MSG_D_MJ_KEEP_SEAT_ACTIVE]: [ClientMessageMjKeepSeatActive, null! as ClientMessageMjKeepSeatActive.AsObject],
    [Code.MSG_D_MJ_ADD_TIME]: [ClientMessageMjAddTime, null! as ClientMessageMjAddTime.AsObject],
    [Code.MSG_D_MJ_BROADCAST_MSG]: [ClientMessageMjBroadcastMsg, null! as ClientMessageMjBroadcastMsg.AsObject],
    [Code.MSG_D_MJ_PRIVATE_MSG]: [ClientMessageMjPrivateMsg, null! as ClientMessageMjPrivateMsg.AsObject],
    [Code.MSG_D_MJ_ROOMERS]: [ClientMessageMjRoomers, null! as ClientMessageMjRoomers.AsObject],
    [Code.MSG_D_MJ_SET_AUTO_ON_TABLE]: [ClientMessageMjSetAutoOnTable, null! as ClientMessageMjSetAutoOnTable.AsObject],
    [Code.MSG_D_MJ_OBSERVERS]: [ClientMessageMjObservers, null! as ClientMessageMjObservers.AsObject],
    [Code.MSG_D_MJ_SYNC_ENTER]: [ClientMessageMjSyncEnter, null! as ClientMessageMjSyncEnter.AsObject],
    [Code.MSG_D_MJ_REPLAY]: [ClientMessageMjReplay, null! as ClientMessageMjReplay.AsObject],
    [Code.MSG_D_MJ_CHAT_MEMBERS]: [ClientMessageMjChatMembers, null! as ClientMessageMjChatMembers.AsObject],
    [Code.MSG_D_MJ_RAISE]: [ClientMessageMjRaise, null! as ClientMessageMjRaise.AsObject],
    [Code.MSG_D_MJ_REJECT_BRING_IN]: [ClientMessageMjRejectBringIn, null! as ClientMessageMjRejectBringIn.AsObject]
} as const;

export type CodeMessageMahjongClientGC = typeof CodeMessageMahjongClientGC;

export const CodeMessageMahjongServerGC = {
    [Code.MSG_D_MJ_ENTER_ROOM]: ServerMessageMjEnterRoom,
    [Code.MSG_D_MJ_SEATED]: ServerMessageMjSeated,
    [Code.MSG_D_MJ_BRING_IN]: ServerMessageMjBringIn,
    [Code.MSG_D_MJ_EXCHANGE_TILES]: ServerMessageMjExchangeTiles,
    [Code.MSG_D_MJ_VOID_SUIT]: ServerMessageMjVoidSuit,
    [Code.MSG_D_MJ_ACTION]: ServerMessageMjAction,
    [Code.MSG_D_MJ_AUTO_OP_ACTIVE]: ServerMessageMjAutoOpActive,
    [Code.MSG_D_MJ_STANDUP_ACTIVE]: ServerMessageMjStandupActive,
    [Code.MSG_D_MJ_LEAVE]: ServerMessageMjLeave,
    [Code.MSG_D_MJ_KEEP_SEAT_ACTIVE]: ServerMessageMjKeepSeatActive,
    [Code.MSG_D_MJ_ADD_TIME]: ServerMessageMjAddTime,
    [Code.MSG_D_MJ_BROADCAST_MSG]: ServerMessageMjBroadcastMsg,
    [Code.MSG_D_MJ_PRIVATE_MSG]: ServerMessageMjPrivateMsg,
    [Code.MSG_D_MJ_ROOMERS]: ServerMessageMjRoomers,
    [Code.MSG_D_MJ_SET_AUTO_ON_TABLE]: ServerMessageMjSetAutoOnTable,
    [Code.MSG_D_MJ_OBSERVERS]: ServerMessageMjObservers,
    [Code.MSG_D_MJ_SYNC_ENTER]: ServerMessageMjSyncEnter,
    [Code.MSG_D_MJ_REPLAY]: ServerMessageMjReplay,
    [Code.MSG_D_MJ_CHAT_MEMBERS]: ServerMessageMjChatMembers,
    [Code.MSG_D_MJ_RAISE]: ServerMessageMjRaise,
    [Code.MSG_D_MJ_REJECT_BRING_IN]: ServerMessageMjRejectBringIn,
    [Code.MSG_S_MJ_SEATED_OTHERS]: ServerMessageMjSeatedOthers,
    [Code.MSG_S_MJ_START_INFO]: ServerMessageMjStartInfo,
    [Code.MSG_S_MJ_EXCHANGE_TILES_COMPLETE]: ServerMessageMjExchangeTilesComplete,
    [Code.MSG_S_MJ_VOID_SUIT_COMPLETE]: ServerMessageMjVoidSuitComplete,
    [Code.MSG_S_MJ_CHIPS_CHANGE]: ServerMessageMjChipsChange,
    [Code.MSG_S_MJ_ACTION_ALL]: ServerMessageMjActionAll,
    [Code.MSG_S_MJ_AUTO_OP]: ServerMessageMjAutoOp,
    [Code.MSG_S_MJ_STANDUP]: ServerMessageMjStandup,
    [Code.MSG_S_MJ_KEEP_SEAT]: ServerMessageMjKeepSeat,
    [Code.MSG_S_MJ_RESULT]: ServerMessageMjResult,
    [Code.MSG_S_MJ_ADD_TIME_OTHERS]: ServerMessageMjAddTimeOthers,
    [Code.MSG_S_MJ_LEAVE_NOTIFICATION]: ServerMessageMjLeaveNotification,
    [Code.MSG_S_MJ_BRING_IN_FAIL]: ServerMessageMjBringInFail,
    [Code.MSG_S_MJ_HAND_CLEAR]: ServerMessageMjHandClear,
    [Code.MSG_S_MJ_GET_MSG]: ServerMessageMjGetMsg,
    [Code.MSG_S_MJ_WAIT_TURN_ACTION]: ServerMessageMjWaitTurnAction,
    [Code.MSG_S_MJ_ACTION_FAIL]: ServerMessageMjActionFail,
    [Code.MSG_S_MJ_PREPARE]: ServerMessageMjPrepare,
    [Code.MSG_S_MJ_RAISE_COMPLETE]: ServerMessageMjRaiseComplete,
    [Code.MSG_S_MJ_FOLLOW_DEALER]: ServerMessageMjFollowDealer,
    [Code.MSG_S_MJ_NEED_BRING_IN]: ServerMessageMjNeedBringIn,
    [Code.MSG_S_MJ_NEED_BRING_IN_COMPLETE]: ServerMessageMjNeedBringInComplete,
    [Code.MSG_S_MJ_VIDEO_MASK_CHANGE]: ServerMessageMjVideoMaskChange,
    [Code.MSG_S_MJ_UP_BLIND]: ServerMessageMjUpBlind,
    [Code.MSG_S_MJ_SYNC_HAND]: ServerMessageMjSyncHand
} as const;

export type CodeMessageMahjongServerGC = typeof CodeMessageMahjongServerGC;
