import {
    ClientMessageCbBringIn,
    ClientMessageCbCancelPlay,
    ClientMessageCbChat,
    ClientMessageCbEnterRoom,
    ClientMessageCbLastGames,
    ClientMessageCbLeave,
    ClientMessageCbOnline,
    ClientMessageCbPlay,
    ClientMessageCbSyncEnter,
    ClientMessageCbTop,
    ClientMessageCbWaymap,
    ClientMessageCbWaymapSpec,
    Code,
    ServerMessageCbBringIn,
    ServerMessageCbCancelPlay,
    ServerMessageCbChat,
    ServerMessageCbChatOthers,
    ServerMessageCbEncryptCards,
    ServerMessageCbEnterRoom,
    ServerMessageCbGamePlayEnd,
    ServerMessageCbGamePlayInfo,
    ServerMessageCbGameResult,
    ServerMessageCbGameStart,
    ServerMessageCbLastGames,
    ServerMessageCbLeave,
    ServerMessageCbLeaveNotification,
    ServerMessageCbOnline,
    ServerMessageCbPlay,
    ServerMessageCbRoomClose,
    ServerMessageCbStandupNotification,
    ServerMessageCbSyncEnter,
    ServerMessageCbTop,
    ServerMessageCbWaymap,
    ServerMessageCbWaymapSpec,
    ServerMessageCbWaymapUpdate
} from '@silenthill/agreement-web';

export const CodeMessageCowboyClientGC = {
    [Code.MSG_D_CB_ENTER_ROOM]: [ClientMessageCbEnterRoom, null! as ClientMessageCbEnterRoom.AsObject],
    [Code.MSG_D_CB_PLAY]: [ClientMessageCbPlay, null! as ClientMessageCbPlay.AsObject],
    [Code.MSG_D_CB_CANCEL_PLAY]: [ClientMessageCbCancelPlay, null! as ClientMessageCbCancelPlay.AsObject],
    [Code.MSG_D_CB_LEAVE]: [ClientMessageCbLeave, null! as ClientMessageCbLeave.AsObject],
    [Code.MSG_D_CB_CHAT]: [ClientMessageCbChat, null! as ClientMessageCbChat.AsObject],
    [Code.MSG_D_CB_TOP]: [ClientMessageCbTop, null! as ClientMessageCbTop.AsObject],
    [Code.MSG_D_CB_WAYMAP]: [ClientMessageCbWaymap, null! as ClientMessageCbWaymap.AsObject],
    [Code.MSG_D_CB_LAST_GAMES]: [ClientMessageCbLastGames, null! as ClientMessageCbLastGames.AsObject],
    [Code.MSG_D_CB_BRING_IN]: [ClientMessageCbBringIn, null! as ClientMessageCbBringIn.AsObject],
    [Code.MSG_D_CB_WAYMAP_SPEC]: [ClientMessageCbWaymapSpec, null! as ClientMessageCbWaymapSpec.AsObject],
    [Code.MSG_D_CB_ONLINE]: [ClientMessageCbOnline, null! as ClientMessageCbOnline.AsObject],
    [Code.MSG_D_CB_SYNC_ENTER]: [ClientMessageCbSyncEnter, null! as ClientMessageCbSyncEnter.AsObject]
} as const;

export type CodeMessageCowboyClientGC = typeof CodeMessageCowboyClientGC;

export const CodeMessageCowboyServerGC = {
    [Code.MSG_D_CB_ENTER_ROOM]: ServerMessageCbEnterRoom,
    [Code.MSG_D_CB_PLAY]: ServerMessageCbPlay,
    [Code.MSG_D_CB_CANCEL_PLAY]: ServerMessageCbCancelPlay,
    [Code.MSG_D_CB_LEAVE]: ServerMessageCbLeave,
    [Code.MSG_D_CB_CHAT]: ServerMessageCbChat,
    [Code.MSG_D_CB_TOP]: ServerMessageCbTop,
    [Code.MSG_D_CB_WAYMAP]: ServerMessageCbWaymap,
    [Code.MSG_D_CB_LAST_GAMES]: ServerMessageCbLastGames,
    [Code.MSG_D_CB_BRING_IN]: ServerMessageCbBringIn,
    [Code.MSG_D_CB_WAYMAP_SPEC]: ServerMessageCbWaymapSpec,
    [Code.MSG_D_CB_ONLINE]: ServerMessageCbOnline,
    [Code.MSG_D_CB_SYNC_ENTER]: ServerMessageCbSyncEnter,
    [Code.MSG_S_CB_GAME_START]: ServerMessageCbGameStart,
    [Code.MSG_S_CB_GAME_PLAY_INFO]: ServerMessageCbGamePlayInfo,
    [Code.MSG_S_CB_GAME_PLAY_END]: ServerMessageCbGamePlayEnd,
    [Code.MSG_S_CB_GAME_RESULT]: ServerMessageCbGameResult,
    [Code.MSG_S_CB_WAYMAP_UPDATE]: ServerMessageCbWaymapUpdate,
    [Code.MSG_S_CB_ROOM_CLOSE]: ServerMessageCbRoomClose,
    [Code.MSG_S_CB_CHAT_OTHERS]: ServerMessageCbChatOthers,
    [Code.MSG_S_CB_LEAVE_NOTIFICATION]: ServerMessageCbLeaveNotification,
    [Code.MSG_S_CB_STANDUP_NOTIFICATION]: ServerMessageCbStandupNotification,
    [Code.MSG_S_CB_ENCRYPT_CARDS]: ServerMessageCbEncryptCards
} as const;

export type CodeMessageCowboyServerGC = typeof CodeMessageCowboyServerGC;
