import {
    ClientMessageGdAction,
    ClientMessageGdAddTime,
    ClientMessageGdAutoOpActive,
    ClientMessageGdBringIn,
    ClientMessageGdBroadcastMsg,
    ClientMessageGdChatMembers,
    ClientMessageGdEnterRoom,
    ClientMessageGdKeepSeatActive,
    ClientMessageGdLeave,
    ClientMessageGdObservers,
    ClientMessageGdPrivateMsg,
    ClientMessageGdReadyStart,
    ClientMessageGdReplay,
    ClientMessageGdRoomers,
    ClientMessageGdSeated,
    ClientMessageGdSetAutoOnTable,
    ClientMessageGdStandupActive,
    ClientMessageGdSyncEnter,
    ClientMessageGdTributeGive,
    ClientMessageGdTributeReturn,
    ClientMessageGdWinrateAdd,
    Code,
    ServerMessageGdAction,
    ServerMessageGdActionAll,
    ServerMessageGdAddTime,
    ServerMessageGdAddTimeOthers,
    ServerMessageGdAutoOp,
    ServerMessageGdAutoOpActive,
    ServerMessageGdBringIn,
    ServerMessageGdBringInFail,
    ServerMessageGdBroadcastMsg,
    ServerMessageGdChatMembers,
    ServerMessageGdChipsChange,
    ServerMessageGdEnterRoom,
    ServerMessageGdGetMsg,
    ServerMessageGdHandClear,
    ServerMessageGdKeepSeat,
    ServerMessageGdKeepSeatActive,
    ServerMessageGdLeave,
    ServerMessageGdLeaveNotification,
    ServerMessageGdObservers,
    ServerMessageGdPrivateMsg,
    ServerMessageGdReadyStart,
    ServerMessageGdReadyStartAll,
    ServerMessageGdReplay,
    ServerMessageGdResult,
    ServerMessageGdRoomers,
    ServerMessageGdSeated,
    ServerMessageGdSeatedOthers,
    ServerMessageGdSetAutoOnTable,
    ServerMessageGdStandup,
    ServerMessageGdStandupActive,
    ServerMessageGdStartInfo,
    ServerMessageGdSyncEnter,
    ServerMessageGdTributeGive,
    ServerMessageGdTributeGiveComplete,
    ServerMessageGdTributeReturn,
    ServerMessageGdTributeReturnComplete,
    ServerMessageGdVideoMaskChange,
    ServerMessageGdWaitReadyStart,
    ServerMessageGdWinrateAdd,
    ServerMessageGdWinrateAddComplete
} from '@silenthill/agreement-web';

export const CodeMessageGuandanClientGC = {
    [Code.MSG_D_GD_ENTER_ROOM]: [ClientMessageGdEnterRoom, null! as ClientMessageGdEnterRoom.AsObject],
    [Code.MSG_D_GD_SEATED]: [ClientMessageGdSeated, null! as ClientMessageGdSeated.AsObject],
    [Code.MSG_D_GD_BRING_IN]: [ClientMessageGdBringIn, null! as ClientMessageGdBringIn.AsObject],
    [Code.MSG_D_GD_READY_START]: [ClientMessageGdReadyStart, null! as ClientMessageGdReadyStart.AsObject],
    [Code.MSG_D_GD_WINRATE_ADD]: [ClientMessageGdWinrateAdd, null! as ClientMessageGdWinrateAdd.AsObject],
    [Code.MSG_D_GD_TRIBUTE_GIVE]: [ClientMessageGdTributeGive, null! as ClientMessageGdTributeGive.AsObject],
    [Code.MSG_D_GD_TRIBUTE_RETURN]: [ClientMessageGdTributeReturn, null! as ClientMessageGdTributeReturn.AsObject],
    [Code.MSG_D_GD_ACTION]: [ClientMessageGdAction, null! as ClientMessageGdAction.AsObject],
    [Code.MSG_D_GD_AUTO_OP_ACTIVE]: [ClientMessageGdAutoOpActive, null! as ClientMessageGdAutoOpActive.AsObject],
    [Code.MSG_D_GD_STANDUP_ACTIVE]: [ClientMessageGdStandupActive, null! as ClientMessageGdStandupActive.AsObject],
    [Code.MSG_D_GD_LEAVE]: [ClientMessageGdLeave, null! as ClientMessageGdLeave.AsObject],
    [Code.MSG_D_GD_KEEP_SEAT_ACTIVE]: [ClientMessageGdKeepSeatActive, null! as ClientMessageGdKeepSeatActive.AsObject],
    [Code.MSG_D_GD_ADD_TIME]: [ClientMessageGdAddTime, null! as ClientMessageGdAddTime.AsObject],
    [Code.MSG_D_GD_BROADCAST_MSG]: [ClientMessageGdBroadcastMsg, null! as ClientMessageGdBroadcastMsg.AsObject],
    [Code.MSG_D_GD_PRIVATE_MSG]: [ClientMessageGdPrivateMsg, null! as ClientMessageGdPrivateMsg.AsObject],
    [Code.MSG_D_GD_ROOMERS]: [ClientMessageGdRoomers, null! as ClientMessageGdRoomers.AsObject],
    [Code.MSG_D_GD_SET_AUTO_ON_TABLE]: [ClientMessageGdSetAutoOnTable, null! as ClientMessageGdSetAutoOnTable.AsObject],
    [Code.MSG_D_GD_OBSERVERS]: [ClientMessageGdObservers, null! as ClientMessageGdObservers.AsObject],
    [Code.MSG_D_GD_SYNC_ENTER]: [ClientMessageGdSyncEnter, null! as ClientMessageGdSyncEnter.AsObject],
    [Code.MSG_D_GD_REPLAY]: [ClientMessageGdReplay, null! as ClientMessageGdReplay.AsObject],
    [Code.MSG_D_GD_CHAT_MEMBERS]: [ClientMessageGdChatMembers, null! as ClientMessageGdChatMembers.AsObject]
} as const;

export type CodeMessageGuandanClientGC = typeof CodeMessageGuandanClientGC;

export const CodeMessageGuandanServerGC = {
    [Code.MSG_D_GD_ENTER_ROOM]: ServerMessageGdEnterRoom,
    [Code.MSG_D_GD_SEATED]: ServerMessageGdSeated,
    [Code.MSG_D_GD_BRING_IN]: ServerMessageGdBringIn,
    [Code.MSG_D_GD_READY_START]: ServerMessageGdReadyStart,
    [Code.MSG_D_GD_WINRATE_ADD]: ServerMessageGdWinrateAdd,
    [Code.MSG_D_GD_TRIBUTE_GIVE]: ServerMessageGdTributeGive,
    [Code.MSG_D_GD_TRIBUTE_RETURN]: ServerMessageGdTributeReturn,
    [Code.MSG_D_GD_ACTION]: ServerMessageGdAction,
    [Code.MSG_D_GD_AUTO_OP_ACTIVE]: ServerMessageGdAutoOpActive,
    [Code.MSG_D_GD_STANDUP_ACTIVE]: ServerMessageGdStandupActive,
    [Code.MSG_D_GD_LEAVE]: ServerMessageGdLeave,
    [Code.MSG_D_GD_KEEP_SEAT_ACTIVE]: ServerMessageGdKeepSeatActive,
    [Code.MSG_D_GD_ADD_TIME]: ServerMessageGdAddTime,
    [Code.MSG_D_GD_BROADCAST_MSG]: ServerMessageGdBroadcastMsg,
    [Code.MSG_D_GD_PRIVATE_MSG]: ServerMessageGdPrivateMsg,
    [Code.MSG_D_GD_ROOMERS]: ServerMessageGdRoomers,
    [Code.MSG_D_GD_SET_AUTO_ON_TABLE]: ServerMessageGdSetAutoOnTable,
    [Code.MSG_D_GD_OBSERVERS]: ServerMessageGdObservers,
    [Code.MSG_D_GD_SYNC_ENTER]: ServerMessageGdSyncEnter,
    [Code.MSG_D_GD_REPLAY]: ServerMessageGdReplay,
    [Code.MSG_D_GD_CHAT_MEMBERS]: ServerMessageGdChatMembers,
    [Code.MSG_S_GD_SEATED_OTHERS]: ServerMessageGdSeatedOthers,
    [Code.MSG_S_GD_START_INFO]: ServerMessageGdStartInfo,
    [Code.MSG_S_GD_WINRATE_ADD_COMPLETE]: ServerMessageGdWinrateAddComplete,
    [Code.MSG_S_GD_TRIBUTE_GIVE_COMPLETE]: ServerMessageGdTributeGiveComplete,
    [Code.MSG_S_GD_TRIBUTE_RETURN_COMPLETE]: ServerMessageGdTributeReturnComplete,
    [Code.MSG_S_GD_CHIPS_CHANGE]: ServerMessageGdChipsChange,
    [Code.MSG_S_GD_ACTION_ALL]: ServerMessageGdActionAll,
    [Code.MSG_S_GD_AUTO_OP]: ServerMessageGdAutoOp,
    [Code.MSG_S_GD_STANDUP]: ServerMessageGdStandup,
    [Code.MSG_S_GD_KEEP_SEAT]: ServerMessageGdKeepSeat,
    [Code.MSG_S_GD_RESULT]: ServerMessageGdResult,
    [Code.MSG_S_GD_ADD_TIME_OTHERS]: ServerMessageGdAddTimeOthers,
    [Code.MSG_S_GD_LEAVE_NOTIFICATION]: ServerMessageGdLeaveNotification,
    [Code.MSG_S_GD_BRING_IN_FAIL]: ServerMessageGdBringInFail,
    [Code.MSG_S_GD_HAND_CLEAR]: ServerMessageGdHandClear,
    [Code.MSG_S_GD_GET_MSG]: ServerMessageGdGetMsg,
    [Code.MSG_S_GD_READY_START_ALL]: ServerMessageGdReadyStartAll,
    [Code.MSG_S_GD_WAIT_READY_START]: ServerMessageGdWaitReadyStart,
    [Code.MSG_S_GD_VIDEO_MASK_CHANGE]: ServerMessageGdVideoMaskChange
} as const;

export type CodeMessageGuandanServerGC = typeof CodeMessageGuandanServerGC;
