import {
    ClientMessageHeartbeat,
    ClientMessageJoinMatching,
    ClientMessageMttDetail,
    ClientMessageQuickJoin,
    ClientMessageRegister,
    ClientMessageRooms,
    ClientMessageRoomsSimple,
    ClientMessageUserPlaying,
    Code,
    ServerMessageAdminRoomUserLeave,
    ServerMessageAdminRoomUserStandup,
    ServerMessageCacheDataUpdate,
    ServerMessageClubRoomBringInApplyAudit,
    ServerMessageClubRoomBringInApplyToAdmin,
    ServerMessageClubRoomBringInApplyToUser,
    ServerMessageClubRoomDelayApplyAudit,
    ServerMessageClubRoomMttSettleNotify,
    ServerMessageClubUserIsBlocked,
    ServerMessageError,
    ServerMessageFriendRoomBringInApplyToAdmin,
    ServerMessageFriendRoomBringInApplyToUser,
    ServerMessageFriendRoomCreatorSettle,
    ServerMessageGetMessage,
    ServerMessageHeartbeat,
    ServerMessageJackpotMarquee,
    ServerMessageJoinMatching,
    ServerMessageLimitHandNumber,
    ServerMessageMatchingResult,
    ServerMessageMttAwardNotify,
    ServerMessageMttDetail,
    ServerMessageMttReadyForApply,
    ServerMessageMttSeriesNotify,
    ServerMessageNotificationMttWillStart,
    ServerMessageNotificationRoomReady,
    ServerMessageNotificationSystemMaintain,
    ServerMessageOfflineTickets,
    ServerMessageQuickJoin,
    ServerMessageRegister,
    ServerMessageRoomChangeNotify,
    ServerMessageRoomDelayApplyToAdmin,
    ServerMessageRoomMttSettleNotify,
    ServerMessageRoomReadyForEnter,
    ServerMessageRooms,
    ServerMessageRoomsSimple,
    ServerMessageRoomUserSendDiamond,
    ServerMessageSelfProfitPay,
    ServerMessageSnatchTreasureHrl,
    ServerMessageSnatchTreasureWinPopup,
    ServerMessageSupportMessage,
    ServerMessageSystemMessage,
    ServerMessageTodoList,
    ServerMessageTribeBlackUser,
    ServerMessageTribeBlackUserMtt,
    ServerMessageUserBan,
    ServerMessageUserClubRoleChange,
    ServerMessageUserDeviceIsBlocked,
    ServerMessageUserDiamondChange,
    ServerMessageUserGameWatch,
    ServerMessageUserGoldChange,
    ServerMessageUserIsBlocked,
    ServerMessageUserIsMute,
    ServerMessageUserJoinClub,
    ServerMessageUserKickedFromClub,
    ServerMessageUserMttChangeNotify,
    ServerMessageUserOrderAudit,
    ServerMessageUserPlaying,
    ServerMessageUserSngChangeNotify,
    ServerMessageUserTraderOrderNotify,
    ServerMessageUserUsdtOrderNotify,
    ServerMessageUserWheelHandNum,
    ServerMessageUtilAntiCheatRoomVideo,
    ServerMessageUtilFaceRecognize
} from '@silenthill/agreement-web';

export const CodeMessageOtherClientGC = {
    [Code.MSG_D_REGISTER]: [ClientMessageRegister, null! as ClientMessageRegister.AsObject],
    [Code.MSG_D_HEARTBEAT]: [ClientMessageHeartbeat, null! as ClientMessageHeartbeat.AsObject],
    [Code.MSG_D_USER_PLAYING]: [ClientMessageUserPlaying, null! as ClientMessageUserPlaying.AsObject]
} as const;

export type CodeMessageOtherClientGC = typeof CodeMessageOtherClientGC;

export const CodeMessageRpcClientGC = {
    [Code.MSG_R_ROOMS]: [ClientMessageRooms, null! as ClientMessageRooms.AsObject, ServerMessageRooms, null! as ServerMessageRooms.AsObject],
    [Code.MSG_R_QUICK_JOIN]: [
        ClientMessageQuickJoin,
        null! as ClientMessageQuickJoin.AsObject,
        ServerMessageQuickJoin,
        null! as ServerMessageQuickJoin.AsObject
    ],
    [Code.MSG_R_MTT_DETAIL]: [
        ClientMessageMttDetail,
        null! as ClientMessageMttDetail.AsObject,
        ServerMessageMttDetail,
        null! as ServerMessageMttDetail.AsObject
    ],
    [Code.MSG_R_JOIN_MATCHING]: [
        ClientMessageJoinMatching,
        null! as ClientMessageJoinMatching.AsObject,
        ServerMessageJoinMatching,
        null! as ServerMessageJoinMatching.AsObject
    ],
    [Code.MSG_R_ROOMS_SIMPLE]: [
        ClientMessageRoomsSimple,
        null! as ClientMessageRoomsSimple.AsObject,
        ServerMessageRoomsSimple,
        null! as ServerMessageRoomsSimple.AsObject
    ]
} as const;

export type CodeMessageRpcClientGC = typeof CodeMessageRpcClientGC;

export const CodeMessageOtherServerGC = {
    [Code.MSG_D_REGISTER]: ServerMessageRegister,
    [Code.MSG_D_HEARTBEAT]: ServerMessageHeartbeat,
    [Code.MSG_D_USER_PLAYING]: ServerMessageUserPlaying,
    [Code.MSG_R_ROOMS]: ServerMessageRooms,
    [Code.MSG_R_QUICK_JOIN]: ServerMessageQuickJoin,
    [Code.MSG_R_MTT_DETAIL]: ServerMessageMttDetail,
    [Code.MSG_R_JOIN_MATCHING]: ServerMessageJoinMatching,
    [Code.MSG_R_ROOMS_SIMPLE]: ServerMessageRoomsSimple,
    [Code.MSG_S_ERROR]: ServerMessageError,
    [Code.MSG_S_NOTIFICATION_ROOM_READY]: ServerMessageNotificationRoomReady,
    [Code.MSG_S_USER_BAN]: ServerMessageUserBan,
    [Code.MSG_S_NOTIFICATION_SYSTEM_MAINTAIN]: ServerMessageNotificationSystemMaintain,
    [Code.MSG_S_ROOM_READY_FOR_ENTER]: ServerMessageRoomReadyForEnter,
    [Code.MSG_S_MTT_READY_FOR_APPLY]: ServerMessageMttReadyForApply,
    [Code.MSG_S_USER_KICKED_FROM_CLUB]: ServerMessageUserKickedFromClub,
    [Code.MSG_S_NOTIFICATION_MTT_WILL_START]: ServerMessageNotificationMttWillStart,
    [Code.MSG_S_SYSTEM_MESSAGE]: ServerMessageSystemMessage,
    [Code.MSG_S_GET_MESSAGE]: ServerMessageGetMessage,
    [Code.MSG_S_USER_GAME_WATCH]: ServerMessageUserGameWatch,
    [Code.MSG_S_FRIEND_ROOM_BRING_IN_APPLY_TO_ADMIN]: ServerMessageFriendRoomBringInApplyToAdmin,
    [Code.MSG_S_FRIEND_ROOM_BRING_IN_APPLY_TO_USER]: ServerMessageFriendRoomBringInApplyToUser,
    [Code.MSG_S_CLUB_ROOM_BRING_IN_APPLY_TO_ADMIN]: ServerMessageClubRoomBringInApplyToAdmin,
    [Code.MSG_S_CLUB_ROOM_BRING_IN_APPLY_TO_USER]: ServerMessageClubRoomBringInApplyToUser,
    [Code.MSG_S_CLUB_ROOM_BRING_IN_APPLY_AUDIT]: ServerMessageClubRoomBringInApplyAudit,
    [Code.MSG_S_ADMIN_ROOM_USER_STANDUP]: ServerMessageAdminRoomUserStandup,
    [Code.MSG_S_ADMIN_ROOM_USER_LEAVE]: ServerMessageAdminRoomUserLeave,
    [Code.MSG_S_ROOM_DELAY_APPLY_TO_ADMIN]: ServerMessageRoomDelayApplyToAdmin,
    [Code.MSG_S_CLUB_ROOM_DELAY_APPLY_AUDIT]: ServerMessageClubRoomDelayApplyAudit,
    [Code.MSG_S_USER_IS_BLOCKED]: ServerMessageUserIsBlocked,
    [Code.MSG_S_CLUB_USER_IS_BLOCKED]: ServerMessageClubUserIsBlocked,
    [Code.MSG_S_TODO_LIST]: ServerMessageTodoList,
    [Code.MSG_S_USER_DEVICE_IS_BLOCKED]: ServerMessageUserDeviceIsBlocked,
    [Code.MSG_S_OFFLINE_TICKETS]: ServerMessageOfflineTickets,
    [Code.MSG_S_SNATCH_TREASURE_HRL]: ServerMessageSnatchTreasureHrl,
    [Code.MSG_S_SNATCH_TREASURE_WIN_POPUP]: ServerMessageSnatchTreasureWinPopup,
    [Code.MSG_S_JACKPOT_MARQUEE]: ServerMessageJackpotMarquee,
    [Code.MSG_S_MATCHING_RESULT]: ServerMessageMatchingResult,
    [Code.MSG_S_SELF_PROFIT_PAY]: ServerMessageSelfProfitPay,
    [Code.MSG_S_LIMIT_HAND_NUMBER]: ServerMessageLimitHandNumber,
    [Code.MSG_S_ROOM_USER_SEND_DIAMOND]: ServerMessageRoomUserSendDiamond,
    [Code.MSG_S_USER_ORDER_AUDIT]: ServerMessageUserOrderAudit,
    [Code.MSG_S_USER_WHEEL_HAND_NUM]: ServerMessageUserWheelHandNum,
    [Code.MSG_S_CACHE_DATA_UPDATE]: ServerMessageCacheDataUpdate,
    [Code.MSG_S_SUPPORT_MESSAGE]: ServerMessageSupportMessage,
    [Code.MSG_S_USER_IS_MUTE]: ServerMessageUserIsMute,
    [Code.MSG_S_USER_DIAMOND_CHANGE]: ServerMessageUserDiamondChange,
    [Code.MSG_S_TRIBE_BLACK_USER_MTT]: ServerMessageTribeBlackUserMtt,
    [Code.MSG_S_ROOM_CHANGE_NOTIFY]: ServerMessageRoomChangeNotify,
    [Code.MSG_S_USER_GOLD_CHANGE]: ServerMessageUserGoldChange,
    [Code.MSG_S_TRIBE_BLACK_USER]: ServerMessageTribeBlackUser,
    [Code.MSG_S_USER_TRADER_ORDER_NOTIFY]: ServerMessageUserTraderOrderNotify,
    [Code.MSG_S_ROOM_MTT_SETTLE_NOTIFY]: ServerMessageRoomMttSettleNotify,
    [Code.MSG_S_USER_USDT_ORDER_NOTIFY]: ServerMessageUserUsdtOrderNotify,
    [Code.MSG_S_FRIEND_ROOM_CREATOR_SETTLE]: ServerMessageFriendRoomCreatorSettle,
    [Code.MSG_S_MTT_AWARD_NOTIFY]: ServerMessageMttAwardNotify,
    [Code.MSG_S_USER_JOIN_CLUB]: ServerMessageUserJoinClub,
    [Code.MSG_S_CLUB_ROOM_MTT_SETTLE_NOTIFY]: ServerMessageClubRoomMttSettleNotify,
    [Code.MSG_S_USER_CLUB_ROLE_CHANGE]: ServerMessageUserClubRoleChange,
    [Code.MSG_S_USER_MTT_CHANGE_NOTIFY]: ServerMessageUserMttChangeNotify,
    [Code.MSG_S_USER_SNG_CHANGE_NOTIFY]: ServerMessageUserSngChangeNotify,
    [Code.MSG_S_MTT_SERIES_NOTIFY]: ServerMessageMttSeriesNotify,
    [Code.MSG_S_UTIL_FACE_RECOGNIZE]: ServerMessageUtilFaceRecognize,
    [Code.MSG_S_UTIL_ANTI_CHEAT_ROOM_VIDEO]: ServerMessageUtilAntiCheatRoomVideo
} as const;

export type CodeMessageOtherServerGC = typeof CodeMessageOtherServerGC;
