import {
    ClientMessageAction,
    ClientMessageAddOn,
    ClientMessageAddTime,
    ClientMessageAgreePost,
    ClientMessageAgreeSecondPcsActive,
    ClientMessageAutoOpActive,
    ClientMessageBringIn,
    ClientMessageBroadcastMsg,
    ClientMessageBuyInsuranceActive,
    ClientMessageChatMembers,
    ClientMessageEnterRoom,
    ClientMessageKeepSeatActive,
    ClientMessageLeave,
    ClientMessageObservers,
    ClientMessagePlayerJackpotSummary,
    ClientMessagePrivateMsg,
    ClientMessagePublicReplay,
    ClientMessageRoomers,
    ClientMessageRoomInsurance,
    ClientMessageSeated,
    ClientMessageSetAutoOnTable,
    ClientMessageShowdown,
    ClientMessageShowPublicCards,
    ClientMessageSquidInActive,
    ClientMessageStandupActive,
    ClientMessageStoreChips,
    ClientMessageSyncEnter,
    ClientMessageViewPlayerCards,
    ClientMessageViewPlayerCardsNum,
    Code,
    ServerMessageAction,
    ServerMessageActionAll,
    ServerMessageAddOn,
    ServerMessageAddTime,
    ServerMessageAddTimeOthers,
    ServerMessageAgreePost,
    ServerMessageAgreeSecondPcs,
    ServerMessageAgreeSecondPcsActive,
    ServerMessageAgreeSecondPcsTrigged,
    ServerMessageAutoOp,
    ServerMessageAutoOpActive,
    ServerMessageBringIn,
    ServerMessageBringInOrStoreFail,
    ServerMessageBroadcastMsg,
    ServerMessageBuyInsurance,
    ServerMessageBuyInsuranceActive,
    ServerMessageChatMembers,
    ServerMessageChipsChange,
    ServerMessageEncryptCards,
    ServerMessageEnterRoom,
    ServerMessageForceVideo,
    ServerMessageGetMsg,
    ServerMessageHandClear,
    ServerMessageInsuranceOutsCards,
    ServerMessageInsuranceTrigged,
    ServerMessageJackpotAward,
    ServerMessageJackpotGoldChange,
    ServerMessageKeepSeat,
    ServerMessageKeepSeatActive,
    ServerMessageLeave,
    ServerMessageLeaveNotification,
    ServerMessageNextChange,
    ServerMessageObservers,
    ServerMessagePlayerJackpotSummary,
    ServerMessagePostStatusChange,
    ServerMessagePrivateMsg,
    ServerMessagePublicCards,
    ServerMessagePublicReplay,
    ServerMessageRoomers,
    ServerMessageRoomInsurance,
    ServerMessageSeated,
    ServerMessageSeatedOthers,
    ServerMessageSetAutoOnTable,
    ServerMessageShowcards,
    ServerMessageShowdown,
    ServerMessageShowPublicCards,
    ServerMessageShowPublicCardsOthers,
    ServerMessageShowViewCards,
    ServerMessageSidePots,
    ServerMessageSquidIn,
    ServerMessageSquidInActive,
    ServerMessageStandup,
    ServerMessageStandupActive,
    ServerMessageStartInfo,
    ServerMessageStoreChips,
    ServerMessageSyncEnter,
    ServerMessageSyncHand,
    ServerMessageUpBlind,
    ServerMessageVideoMaskChange,
    ServerMessageViewPlayerCards,
    ServerMessageViewPlayerCardsNum,
    ServerMessageWaitCheckAutoAddTime,
    ServerMessageWinner
} from '@silenthill/agreement-web';

export const CodeMessageTexasClientGC = {
    [Code.MSG_D_ENTER_ROOM]: [ClientMessageEnterRoom, null! as ClientMessageEnterRoom.AsObject],
    [Code.MSG_D_SEATED]: [ClientMessageSeated, null! as ClientMessageSeated.AsObject],
    [Code.MSG_D_ADD_ON]: [ClientMessageAddOn, null! as ClientMessageAddOn.AsObject],
    [Code.MSG_D_BRING_IN]: [ClientMessageBringIn, null! as ClientMessageBringIn.AsObject],
    [Code.MSG_D_ACTION]: [ClientMessageAction, null! as ClientMessageAction.AsObject],
    [Code.MSG_D_AUTO_OP_ACTIVE]: [ClientMessageAutoOpActive, null! as ClientMessageAutoOpActive.AsObject],
    [Code.MSG_D_SET_AUTO_ON_TABLE]: [ClientMessageSetAutoOnTable, null! as ClientMessageSetAutoOnTable.AsObject],
    [Code.MSG_D_STANDUP_ACTIVE]: [ClientMessageStandupActive, null! as ClientMessageStandupActive.AsObject],
    [Code.MSG_D_LEAVE]: [ClientMessageLeave, null! as ClientMessageLeave.AsObject],
    [Code.MSG_D_KEEP_SEAT_ACTIVE]: [ClientMessageKeepSeatActive, null! as ClientMessageKeepSeatActive.AsObject],
    [Code.MSG_D_SHOWDOWN]: [ClientMessageShowdown, null! as ClientMessageShowdown.AsObject],
    [Code.MSG_D_SHOW_PUBLIC_CARDS]: [ClientMessageShowPublicCards, null! as ClientMessageShowPublicCards.AsObject],
    [Code.MSG_D_ADD_TIME]: [ClientMessageAddTime, null! as ClientMessageAddTime.AsObject],
    [Code.MSG_D_BUY_INSURANCE_ACTIVE]: [ClientMessageBuyInsuranceActive, null! as ClientMessageBuyInsuranceActive.AsObject],
    [Code.MSG_D_AGREE_POST]: [ClientMessageAgreePost, null! as ClientMessageAgreePost.AsObject],
    [Code.MSG_D_STORE_CHIPS]: [ClientMessageStoreChips, null! as ClientMessageStoreChips.AsObject],
    [Code.MSG_D_PUBLIC_REPLAY]: [ClientMessagePublicReplay, null! as ClientMessagePublicReplay.AsObject],
    [Code.MSG_D_BROADCAST_MSG]: [ClientMessageBroadcastMsg, null! as ClientMessageBroadcastMsg.AsObject],
    [Code.MSG_D_PRIVATE_MSG]: [ClientMessagePrivateMsg, null! as ClientMessagePrivateMsg.AsObject],
    [Code.MSG_D_ROOMERS]: [ClientMessageRoomers, null! as ClientMessageRoomers.AsObject],
    [Code.MSG_D_AGREE_SECOND_PCS_ACTIVE]: [ClientMessageAgreeSecondPcsActive, null! as ClientMessageAgreeSecondPcsActive.AsObject],
    [Code.MSG_D_OBSERVERS]: [ClientMessageObservers, null! as ClientMessageObservers.AsObject],
    [Code.MSG_D_SQUID_IN_ACTIVE]: [ClientMessageSquidInActive, null! as ClientMessageSquidInActive.AsObject],
    [Code.MSG_D_SYNC_ENTER]: [ClientMessageSyncEnter, null! as ClientMessageSyncEnter.AsObject],
    [Code.MSG_D_VIEW_PLAYER_CARDS]: [ClientMessageViewPlayerCards, null! as ClientMessageViewPlayerCards.AsObject],
    [Code.MSG_D_PLAYER_JACKPOT_SUMMARY]: [ClientMessagePlayerJackpotSummary, null! as ClientMessagePlayerJackpotSummary.AsObject],
    [Code.MSG_D_CHAT_MEMBERS]: [ClientMessageChatMembers, null! as ClientMessageChatMembers.AsObject],
    [Code.MSG_D_VIEW_PLAYER_CARDS_NUM]: [ClientMessageViewPlayerCardsNum, null! as ClientMessageViewPlayerCardsNum.AsObject],
    [Code.MSG_D_ROOM_INSURANCE]: [ClientMessageRoomInsurance, null! as ClientMessageRoomInsurance.AsObject]
} as const;

export type CodeMessageTexasClientGC = typeof CodeMessageTexasClientGC;

export const CodeMessageTexasServerGC = {
    [Code.MSG_D_ENTER_ROOM]: ServerMessageEnterRoom,
    [Code.MSG_D_SEATED]: ServerMessageSeated,
    [Code.MSG_D_ADD_ON]: ServerMessageAddOn,
    [Code.MSG_D_BRING_IN]: ServerMessageBringIn,
    [Code.MSG_D_ACTION]: ServerMessageAction,
    [Code.MSG_D_AUTO_OP_ACTIVE]: ServerMessageAutoOpActive,
    [Code.MSG_D_SET_AUTO_ON_TABLE]: ServerMessageSetAutoOnTable,
    [Code.MSG_D_STANDUP_ACTIVE]: ServerMessageStandupActive,
    [Code.MSG_D_LEAVE]: ServerMessageLeave,
    [Code.MSG_D_KEEP_SEAT_ACTIVE]: ServerMessageKeepSeatActive,
    [Code.MSG_D_SHOWDOWN]: ServerMessageShowdown,
    [Code.MSG_D_SHOW_PUBLIC_CARDS]: ServerMessageShowPublicCards,
    [Code.MSG_D_ADD_TIME]: ServerMessageAddTime,
    [Code.MSG_D_BUY_INSURANCE_ACTIVE]: ServerMessageBuyInsuranceActive,
    [Code.MSG_D_AGREE_POST]: ServerMessageAgreePost,
    [Code.MSG_D_STORE_CHIPS]: ServerMessageStoreChips,
    [Code.MSG_D_PUBLIC_REPLAY]: ServerMessagePublicReplay,
    [Code.MSG_D_BROADCAST_MSG]: ServerMessageBroadcastMsg,
    [Code.MSG_D_PRIVATE_MSG]: ServerMessagePrivateMsg,
    [Code.MSG_D_ROOMERS]: ServerMessageRoomers,
    [Code.MSG_D_AGREE_SECOND_PCS_ACTIVE]: ServerMessageAgreeSecondPcsActive,
    [Code.MSG_D_OBSERVERS]: ServerMessageObservers,
    [Code.MSG_D_SQUID_IN_ACTIVE]: ServerMessageSquidInActive,
    [Code.MSG_D_SYNC_ENTER]: ServerMessageSyncEnter,
    [Code.MSG_D_VIEW_PLAYER_CARDS]: ServerMessageViewPlayerCards,
    [Code.MSG_D_PLAYER_JACKPOT_SUMMARY]: ServerMessagePlayerJackpotSummary,
    [Code.MSG_D_CHAT_MEMBERS]: ServerMessageChatMembers,
    [Code.MSG_D_VIEW_PLAYER_CARDS_NUM]: ServerMessageViewPlayerCardsNum,
    [Code.MSG_D_ROOM_INSURANCE]: ServerMessageRoomInsurance,
    [Code.MSG_S_SHOW_PUBLIC_CARDS_OTHERS]: ServerMessageShowPublicCardsOthers,
    [Code.MSG_S_SHOWCARDS]: ServerMessageShowcards,
    [Code.MSG_S_SEATED_OTHERS]: ServerMessageSeatedOthers,
    [Code.MSG_S_START_INFO]: ServerMessageStartInfo,
    [Code.MSG_S_PUBLIC_CARDS]: ServerMessagePublicCards,
    [Code.MSG_S_SIDE_POTS]: ServerMessageSidePots,
    [Code.MSG_S_CHIPS_CHANGE]: ServerMessageChipsChange,
    [Code.MSG_S_ACTION_ALL]: ServerMessageActionAll,
    [Code.MSG_S_AUTO_OP]: ServerMessageAutoOp,
    [Code.MSG_S_STANDUP]: ServerMessageStandup,
    [Code.MSG_S_KEEP_SEAT]: ServerMessageKeepSeat,
    [Code.MSG_S_WINNER]: ServerMessageWinner,
    [Code.MSG_S_ADD_TIME_OTHERS]: ServerMessageAddTimeOthers,
    [Code.MSG_S_LEAVE_NOTIFICATION]: ServerMessageLeaveNotification,
    [Code.MSG_S_INSURANCE_TRIGGED]: ServerMessageInsuranceTrigged,
    [Code.MSG_S_BUY_INSURANCE]: ServerMessageBuyInsurance,
    [Code.MSG_S_POST_STATUS_CHANGE]: ServerMessagePostStatusChange,
    [Code.MSG_S_BRING_IN_OR_STORE_FAIL]: ServerMessageBringInOrStoreFail,
    [Code.MSG_S_HAND_CLEAR]: ServerMessageHandClear,
    [Code.MSG_S_UP_BLIND]: ServerMessageUpBlind,
    [Code.MSG_S_GET_MSG]: ServerMessageGetMsg,
    [Code.MSG_S_AGREE_SECOND_PCS_TRIGGED]: ServerMessageAgreeSecondPcsTrigged,
    [Code.MSG_S_AGREE_SECOND_PCS]: ServerMessageAgreeSecondPcs,
    [Code.MSG_S_SYNC_HAND]: ServerMessageSyncHand,
    [Code.MSG_S_SQUID_IN]: ServerMessageSquidIn,
    [Code.MSG_S_NEXT_CHANGE]: ServerMessageNextChange,
    [Code.MSG_S_SHOW_VIEW_CARDS]: ServerMessageShowViewCards,
    [Code.MSG_S_ENCRYPT_CARDS]: ServerMessageEncryptCards,
    [Code.MSG_S_JACKPOT_GOLD_CHANGE]: ServerMessageJackpotGoldChange,
    [Code.MSG_S_JACKPOT_AWARD]: ServerMessageJackpotAward,
    [Code.MSG_S_INSURANCE_OUTS_CARDS]: ServerMessageInsuranceOutsCards,
    [Code.MSG_S_FORCE_VIDEO]: ServerMessageForceVideo,
    [Code.MSG_S_VIDEO_MASK_CHANGE]: ServerMessageVideoMaskChange,
    [Code.MSG_S_WAIT_CHECK_AUTO_ADD_TIME]: ServerMessageWaitCheckAutoAddTime
} as const;

export type CodeMessageTexasServerGC = typeof CodeMessageTexasServerGC;
